version: '2'
services:
  jhipsterstorereact-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/jhipsterStoreReact/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipsterStoreReact
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
